abrigo_animais/urls.py
from django.urls import path
from abrigo_animais.views import pagina_inicial, card_animais, contribuinte, pedido_adocao, pesquisar_animais, status, sobre, fale_conosco


urlpatterns = [
    path("", pagina_inicial, name='Abrigo_de_Animais'),
    path("animais/<int:id>", card_animais, name='Card_Animais'),
    path("contribuinte/", contribuinte, name='Contribuinte'),
    path("adoção/", pedido_adocao, name='Adoção'),
    path('pesquisar_animais/', pesquisar_animais, name="Pesquisar_Animais"),
    path('verificar_status/<int:pedido_id>/', status, name='Status'),
    path("sobre/", sobre, name='Sobre'),
    path("fale_conosco/", fale_conosco, name='Fale_Conosco')
] 

animais/urls.py
from django.urls import path
from animais.views import cadastro_animal

app_name = 'animais'

urlpatterns = [
  path('cadastro_animal/', cadastro_animal, name='Cadastro_Animal'),
]

cadastro/urls.py
from django.urls import path
from cadastro.views import cadastro_usuario

app_name = 'usuarios'

urlpatterns = [
  path('cadastro_usuario/', cadastro_usuario, name='Cadastro_Usuario')
]

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Credencial

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='Login'),
  path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
  path('credencial/', Credencial.as_view(), name='Credencial')
]

projeto_animais/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("abrigo_animais.urls")),
    path("animais/", include("animais.urls")),
    path("cadastro/", include("cadastro.urls")),
    path("", include("login.urls")),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abrigo_animais/models.py
from django.db import models
from django.contrib.auth.models import User
from animais.models import CadastroAnimal
from django.core.validators import MinValueValidator

class PedidoAdocao(models.Model):
    tipo_solicitação = (
        ("Aceito", "Aceito"),
        ("Recusado", "Recusado"),
        ("Em análise", "Em análise")
    )

    # Cria classe do formulario para o modelo
    #user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=120)
    email=models.EmailField()
    endereço=models.CharField(max_length=120)
    contato=models.IntegerField(validators=[MinValueValidator(0)])
    animal = models.ForeignKey(CadastroAnimal, on_delete=models.DO_NOTHING)
    solicitação=models.CharField(max_length=30, choices=tipo_solicitação)
    cuidados_com_animal=models.TextField()

    def __str__(self):
        return f"[{self.nome}] [{self.email}] [{self.endereço}] [{self.contato}] [{self.solicitação}]"
    
    # Associa formulario ao modelo
    class Meta:
        verbose_name = "Formulário de Adoção de Animal"
        verbose_name_plural = "Formulários de Adoções de Animais"
        ordering = ["solicitação"]

class FaleConosco(models.Model):
  nome = models.CharField(max_length=100)
  email = models.EmailField()
  mensagem = models.TextField()

  def __str__(self) -> str:
    return f"[{self.nome}] [{self.email}] [{self.mensagem}]"
  
  class Meta: 
    verbose_name = "Formulário de contato"
    verbose_name_plural = "Formulários de contato"
    ordering = ["nome"]

cadastro/models.py
from django.db import models
from django.forms import CharField
from django.core.validators import MinValueValidator

class CadastroUsuario(models.Model):

    sexo_tipo = (
        ("f", "Feminino"),
        ("m", "Masculino"),
    )
    
    tipo_funcao = (
        ("c", "Cuidador"),
        ("v", "Voluntário"),
    )

    # Cria classe do formulario para o modelo
    nome_completo = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=77)
    CPF = models.CharField(max_length=11)
    data_nascimento = models.DateField(help_text="dd/mm/aaaa")
    sexo = models.CharField(max_length=10, choices=sexo_tipo)
    funcao = models.CharField(max_length=10, choices=tipo_funcao)
    contato = models.IntegerField(validators=[MinValueValidator(0)])
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=255)
    foto = models.ImageField(upload_to="uploads/", blank=True, null=True)

    def __str__(self):
        return f"{self.nome_completo} [{self.CPF}] [{self.data_nascimento}] [{self.sexo}] [{self.funcao}] [{self.contato}] [{self.foto}]"
    
    # Associa formulario ao modelo
    class Meta:
        verbose_name = "Formulário de Cadastro do Contribuinte"
        verbose_name_plural = "Formulários de Cadastros dos Contribuintes"
        ordering = ["CPF"]

abrigo_animais/forms.py
from dataclasses import fields
from django import forms
from .models import PedidoAdocao, FaleConosco

class PedidoAdocaoForm(forms.ModelForm):
    class Meta:
        model = PedidoAdocao
        fields = ["nome", "email", "endereço", "contato", "animal", "cuidados_com_animal"]
class FaleConoscoForm(forms.ModelForm):
    class Meta:
        model = FaleConosco
        fields = ["nome", "email", "mensagem"]

abrigo_animais/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from abrigo_animais.forms import PedidoAdocaoForm, FaleConoscoForm
from animais.models import CadastroAnimal
from cadastro.models import CadastroUsuario
from abrigo_animais.models import PedidoAdocao
from abrigo_animais.filters import AnimalFilter


def inicio(request):
    return render(request, "index.html")

def pagina_inicial(request):

    animais = CadastroAnimal.objects.all()

    return render(request, "pagina_inicial.html", {'animais': animais})


def card_animais(request, id):

    card = CadastroAnimal.objects.get(id = id)
    
    return render(request, "card_animais.html", {'card': card})

def contribuinte(request):
    contribuinte = CadastroUsuario.objects.all()

    return render(request, "contribuinte.html", {'cadastro': contribuinte})

def pesquisar_animais(request):

    query = request.GET.get('q')
    has_results = False
    animal_filter = None

    if query:
        animal_filter = AnimalFilter(
            data = {'search': query}, queryset=CadastroAnimal.objects.all()
        )
        has_results = animal_filter.qs.exists()
    return render(request,'pesquisar_animais.html', {'filter':animal_filter, 'has_results':has_results})

  
@login_required
def pedido_adocao(request):
        
    # Valida e salva o formulário   
    if request.method == 'POST':

            # Cria formulário
        form = PedidoAdocaoForm(request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('Abrigo_de_Animais')
    else:
        form = PedidoAdocaoForm()

    # Chama Template
    return render(request, 'pedido_adocao.html', {'form': form})

@login_required
def status(request, pedido_id):

    pedido = get_object_or_404(PedidoAdocao, pk=pedido_id)

    if request.user.is_authenticated and pedido.user == request.user:
        return render(request, 'status.html', {'pedido': pedido})
    else:
        return redirect('login')

def sobre(request):
    return render(request, "sobre.html")

def fale_conosco(request):
   sucesso = False   
   form = FaleConoscoForm(request.POST or None)
   if form.is_valid(): 
    sucesso = True
    form.save()
   contexto = {
      'form':form,
      'sucesso': sucesso
   }
   return render(request, "fale_conosco.html", contexto)

abrigo_animais/templates/card_animais.html
{% extends 'index.html' %}
{% load static %}

{% block principal %}
<div class="container">
    <p class="texto__titulo"><strong>Informações detalhadas sobre {{ card.nome }}</strong></p>
    <div class="row d-flex align-items-center justify-content-center mx-3">
            <div class="col-4 rounded">
                <img src="{{ card.foto.url }}" class="rounded-5 w-100" alt="...">
            </div>
            <div class="col-3">
                <strong>Nome:</strong> {{ card.nome }}<br>
                <strong>Espécie:</strong> {{ card.espécie }}<br>
                <strong>Idade:</strong> {{ card.idade }} anos<br>
                <strong>Raça:</strong> {{ card.raça }}<br>
                <strong>Histórico de Saúde:</strong> {{ card.histórico_de_saúde }}<br>
            </div>
        
    </div>

    <br>

    <div class="card_botao">
        <a href="{% url 'Adoção' %}" class="botao_saiba_mais">Requisitar Adoção</a>
        <a href="{% url 'Abrigo_de_Animais' %}" class="botao_cadastro">Voltar para Página Inicial</a>
    </div>
</div>

{% endblock %}

abrigo_animais/templates/contribuinte.html
{% extends 'index.html' %}

<main class="main">
  {% block principal %}
  <h2 class="texto__titulo"><strong>Contribuintes</strong></h2><br>
  <div class="container">
    <div class="row justify-content-center">
      {% for contribuinte in cadastro %}
      <div class="mb-2 mt-2 col-lg-3">
        <div class="card align-items-center">
          <div class="card_foto_2">
            <img src="{{contribuinte.foto.url}}" alt="">
          </div>
          <div class="card_informacao">
            <h5 class="card-title"><strong>{{ contribuinte.nome_completo }}</strong></h5>
          </div>
          <div class="card_informacao">
            <p class="card-text">{{ contribuinte.get_funcao_display }}</p>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="container justify-content-center">
        <div class="row">
          <div class=" col col-md-6 offset-md-3 mx-auto text-center">
            <img class="img_sobre" src="../static/imgs/resultado.png" alt="Resultado">
            <h2><strong></strong>Nenhum contribuente cadastrado.</h2>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
  {% endblock %}
</main>

abrigo_animais/templates/fale_conosco.html
{% extends 'index.html' %}

{% load static %}
{% load bootstrap5 %}

{% block principal %}

<h1 class="texto__titulo"><strong>Entre em Contato com o Abrigo de Animais</strong></h1>

<div class="container justify-content-center">

  <p class="texto__descricao"><strong>Fale Conosco!</strong></p>

  <div class="texto__descricao">
    <p>Estamos localizado na <strong>Av. Luiz de Brito, 001, Matriz, São Paulo-SP, 00000-00</strong></p>
    <p><strong>Contato:</strong> (00) 99999-9999</p>
    <p><strong>E-mail:</strong> email@abrigodeanimais.com.br</p>
  </div>

  <div class="">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Contato</h1>

        {% if sucesso %}
        <div class="alert alert-success col-md-9 mx-auto text-center mb-4" role="alert">
          <h4 class="alert-heading">Contato enviado com sucesso!</h4>
          <hr>
        </div>
        <br><br>
        <div class=" card_botao">
          <a href="{% url 'Fale_Conosco' %}" class="botao_cadastro">Voltar</a>
        </div>
        {% else %}

        <form action="" method="POST">

          {% csrf_token %}
          {% bootstrap_form form %}

          <div class="card_botao">
            <button type="submit" class="botao_cadastro"><strong>Enviar Mensagem</strong></button>

          </div>
        </form>
      </div>
    </div>
  </div>

</div>

<br><br><br>
{% endif %}
{% endblock %}

abrigo_animais/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <title>Abrigo de Animais</title>

  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  <link rel="stylesheet" href="{% static 'style.css' %}">

  <link href="/static/bootstrap.min.css" rel="stylesheet" type="text/css">

  <link rel="shortcut icon" href="{% static 'imgs/logo_cao_e_gato.png' %}" type="image/x-icon">

  <!--Bootstrap  JavaScript-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>

  <!--Bootstrap  JavaScript Bundle-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</head>

<header>
  <nav class="navbar col-12 fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="nav-link active" aria-current="page" href="{% url 'Abrigo_de_Animais' %}">
      <img src="{% static 'imgs/Cachorro_e_Gato_home.png' %}" alt="logo">
    </a>
    
    <div class="container-fluid" col-11 m-auto>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Abrigo_de_Animais' %}">Abrigo de Animais</a>
            {% if user.is_authenticated and user.pedidoadocao_set.all %}
            <a class="nav-link active a-white" aria-current="page"
              href="{% url 'Status' pedido_id=user.pedidoadocao_set.first.id %}">Resultado do pedido de adoção</a>
            {% endif %}
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'Contribuinte' %}">Contribuites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Sobre' %}">Quem Somos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Fale_Conosco' %}">Fale Conosco</a>
          </li>
        </ul>
        <div class="col-md-3 offset-md-4 search-form">
          <form action="{% url 'Pesquisar_Animais' %}" method="get" class="d-flex">
            {% csrf_token %}
            <input class="form-control me-2" name="q" type="search" placeholder="Buscar" aria-label="Search">
            <button class="botao_pesquisar" type="submit"><strong>Pesquisar</strong></button>
          </form>
          </div>

          {% if request.user.is_authenticated %}
          <div class="navbar-nav ms-auto">
            <a class="nav-link a-white">Olá, {{ user.username }}</a>
            <a class="nav-link a-white" href="{% url 'Logout' %}">Sair</a>
          </div>
          {% else %}
          <div class="navbar-nav ms-auto">
            <a class="nav-link a-white" href="{% url 'Credencial' %}">Cadastro</a>
            <a class="nav-link a-white" href="{% url 'Login' %}">Login</a>
          </div>
          {% endif %}
      </div>
    </div>
  </nav>
</header>

<br><br><br>

<body>
  {% block principal %}
  {% endblock %}

  <br><br><br>

  <footer class="footer container-fluid">
    <div class="container">
      <div class="footer__texto text-center" title="Desenvolvedora">
        <strong>Feito pela</strong>
        <img class="icone icone--texto" src="{% static 'imgs/Programadora.png' %}" alt="Desenvolvedora">
        &copy; <strong>Gleiciane Silva</strong>
      </div>
      <div class="icons text-center mb-6">
        <a href="https://www.linkedin.com/in/gleiciane-silva-33737139/" class="col-xs-6 text-center">
          <i class="bi bi-linkedin"></i>
        </a>
        <a href="https://github.com/GleicianeSilva" class="col-xs-6 text-center">
          <i class="bi bi-github"></i>
        </a>
      </div>
    </div>
    {% block footer %}
    {% endblock %}
  </footer>

</body>

</html>

abrigo_animais/templates/pagina_inicial.html
{% extends 'index.html' %}

<main class="main">
    {% block principal %}   
      <h1 class="texto__titulo"><strong>Sejam bem vindos ao Abrigo de Animais</strong></h1><br>
    <div id="carousel_de_imagens" class="carousel slide align-items-center" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="4" aria-label="Slide 5"></button>
        <button type="button" data-bs-target="#carousel_de_imagens" data-bs-slide-to="5" aria-label="Slide 6"></button>
      </div>
      <div class="carousel-inner" >
        <div class="carousel-item active">
          <img src="../static/imgs/Cachorro_Gato.png" class="mx-auto d-flex" alt="Cachorro e Gato">
        </div>
        <div class="carousel-item">
          <img src="../static/imgs/Cachorro_Gato_2.png" class="mx-auto d-flex" alt="Cachorro e Gato">
        </div>
        <div class="carousel-item">
          <img src="../static/imgs/Cachorro_Poodle.png" class="mx-auto d-flex" alt="Cachorro">
        </div>
        <div class="carousel-item">
          <img src="../static/imgs/Cachorro.png" class="mx-auto d-flex" alt="Cachorro">
        </div>
        <div class="carousel-item">
          <img src="../static/imgs/Gato.png" class="mx-auto d-flex" alt="Gato">
        </div>
        <div class="carousel-item">
          <img src="../static/imgs/Gato_2.png" class="mx-auto d-flex" alt="Gato">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel_de_imagens" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="carousel_de_imagens" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Próximo</span>
      </button>
    </div>

    <p class="texto__descricao">
      Animais são pacotinhos de amor embrulhados em pelos! Essas fofurinhas podem trazer ainda mas alegria ao seu coração!
    </p>
   
    <h2 class="topicos"><strong>Adote um animal!</strong></h2><br>
      <div class="container">
        <div class="row justify-content-center">
          {% for animal in animais %}
          <div class="mb-2 mt-2 col-lg-3">
            <div class="card align-items-center">
              <div class="card_foto">
                <img src="{{ animal.foto.url }}" alt="Foto">
              </div>      
              <div class="card_informacao">
                <h5 class="card-title"><strong>{{ animal.nome }}</strong></h5>
              </div>
              <div class="card_botao">
                <a href="{% url 'Card_Animais' animal.id %}" class="botao_saiba_mais"><strong>Saiba Mais</strong></a>
              </div>
            </div>
            <br>
          </div>
      {% empty %}
      <div class="container justify-content-center">
        <div class="row">>
          <div class=" col col-md-6 offset-md-3 mx-auto text-center">
            <img class="img_sobre" src="../static/imgs/resultado.png" alt="Resultado">
            <h2><strong></strong>Nenhum animal cadastrado.</h2>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="card_botao">
        {% if user.is_authenticated and user.pedidoadocao_set.all %}
          <a class="nav-link active a-white" aria-current="page" href="{% url 'Status' pedido_id=user.pedidoadocao_set.first.id %}">Situação de adoção</a>
        {% endif %}
        {% if user.is_authenticated and user.is_staff %}
          <a href="{% url 'animais:Cadastro_Animal' %}" class="botao_cadastro"><strong>Cadastrar Animal</strong></a>
          <a href="{% url 'usuarios:Cadastro_Usuario' %}" class="botao_cadastro"><strong>Cadastrar Usuário</strong></a>
        {% endif %}
      </div>
    </div>
      </div>
</div>
{% endblock %}
</main>

abrigo_animais/templates/pedido_adocao.html
{% extends "index.html" %}
{% load bootstrap5 %}

{% block principal %}

<br><br>

  <div class="container justify-content-center">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h1 class="topicos">Preencha o cadastro para pedido de Adoção de Animais.</h1><br>
        {% if sucesso %}
        <div class="alert alert-success" role="alert">
          <p>Pedido enviado com sucesso.</p>
        </div>
          
        {% else %}
        
        <form action="" method="POST"  id="form" enctype="multipart/form-data">
            
          {% csrf_token %}
          {% bootstrap_form form %}

          <div class="card_botao">
            <input href="{% url 'Abrigo_de_Animais' %}" type="submit" value="Enviar Pedido" class="botao_cadastro">
            <a href="{% url 'Abrigo_de_Animais' %}" class="botao_cadastro">Voltar para Página Inicial</a>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}
  <br><br><br>

{% endblock %}

abrigo_animais/templates/pesquisar_animais.html
{% extends "index.html" %}

<main class="main">
  {% block principal %}
  <br><br><br>
  <h1 class="text-center">Resultado da busca</h1><br>
  {% if has_results %}
  <div class="container">
    <div class="row justify-content-center">
      {% for animal in filter.qs %}
      <div class="mb-2 mt-2 col-lg-3">
        <div class="card align-items-center">
          <div class="card_foto">
            <img src="{{ animal.foto.url }}" alt="...">
          </div>
          <div class="card_informacao text-center">
            <h5 href="{% url 'Card_Animais' animal.id %}" class="card-title">{{ animal.nome }}</h5>
            <p href="{% url 'Card_Animais' animal.id %}" class="card-text">{{ animal.espécie }}</p>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="container justify-content-center">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <h5 class="text-center">Não encontrado.</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  {% else %}
  <div class=" col mx-auto text-center">
    <img class="img_sobre" src="../static/imgs/resultado.png" alt="Resultado">
    <h2><strong></strong>Nenhum animal encontrado.</h2>
  </div>
  {% endif %}


  {% endblock %}



</main>

abrigo_animais/templates/sobre.html
{% extends 'index.html' %}

{% block principal %}


<div class="container justify-content-center">

  <h1  class="texto__titulo"><strong>Abrigo de Animais</strong></h1><br>

  <div class=" col mx-auto text-center">
    <img class="img_sobre" src="../static/imgs/logo_sobre.png" alt="sobre">
  </div>

  <p class="texto__descricao_2 recuo">
    O <strong>Abrigo de Animais</strong> resgata animais que passam fome, frio e medo pelas ruas da cidade. Hoje, o abrigo se encontra no espaço muito pequeno, devido a quantidade de animais que estão sem lar. São mais de 250 animais, todos vacinados, castrados e vermifugados.
    Nosso trabalho é buscar e  tirar estes animais que estão situação de risco e fornecer os cuidados básicos como abrigo, alimentação, recuperação física e emocional, devolvendo-lhes dignidade e segurança, tudo para que possa então estar pronto para a adoção. Buscamos tutores que se comprometam com uma adoção responsável, com cuidados e carinho. Quem convive sabe a felicidade que é ter um animal em casa e só tendo um lar e um dono amoroso um cão é realmente feliz!
    Abrimos as portas para receber os interessados em adotar. Seja nosso coloborador ou voluntario. Venham nos conhecer! :).
  </p>
  <p class="texto__descricao_2 recuo">
    Nosso trabalho é buscar e  tirar estes animais que estão situação de risco e fornecer os cuidados básicos como abrigo, alimentação, recuperação física e emocional, devolvendo-lhes dignidade e segurança, tudo para que possa então estar pronto para a adoção. Buscamos tutores que se comprometam com uma adoção responsável, com cuidados e carinho. Quem convive sabe a felicidade que é ter um animal em casa e só tendo um lar e um dono amoroso um cão é realmente feliz!
  </p>
  <p class="texto__descricao_2 recuo">
    Abrimos as portas para receber os interessados em adotar. Seja nosso coloborador ou voluntario. Venham nos conhecer! :).
  </p>
  <p class="texto__descricao">
    <strong>Venham nos conhecer! :).</strong>
  </p>

</div>

{% endblock %}
    

abrigo_animais/templates/status.html
{% extends 'index.html' %}
{% load bootstrap5 %}


{% block principal %}

<div class="container justify-content-center">
  <div class="row">
    <div class="col-md-6 offset-md-3 ">

      <h2>Status de pedido para Adoção</h2>
      <p><strong>Nome:</strong> {{ pedido.nome }}</p>
      <p><strong>Email:</strong> {{ pedido.email }}</p>
      <p><strong>Animal:</strong> {{ pedido.animal }}</p>
      <p><strong>Cuidados com Animal:</strong> {{ pedido.cuidados_com_animal }}</p>
      <p><strong>Status:</strong> {{ pedido.get_status_display }}</p>
    </div>

  <div class="container text-center">
    <div class="alert alert-info" role="alert">
      <h6><strong>Status:</strong> {{ pedido.get_status_display }}</h6>
    </div>
  </div>
</div>

{% endblock %}